/* Generado por tools/descargar_imagenes.py. No editar a mano. */
window.IMAGENES = {
  "frontal": {
    "file": "frontal.png",
    "titulo": "Frontal bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Frontal_bone_lateral3.png",
    "pagina": "https://en.wikipedia.org/wiki/Frontal_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "parietal": {
    "file": "parietal.png",
    "titulo": "Parietal bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Parietal_bone_posterior2.png",
    "pagina": "https://en.wikipedia.org/wiki/Parietal_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "temporal": {
    "file": "temporal.png",
    "titulo": "Temporal bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Temporal_bone_lateral5.png",
    "pagina": "https://en.wikipedia.org/wiki/Temporal_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "occipital": {
    "file": "occipital.png",
    "titulo": "Occipital bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Occipital_bone_lateral2.png",
    "pagina": "https://en.wikipedia.org/wiki/Occipital_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "esfenoides": {
    "file": "esfenoides.png",
    "titulo": "Sphenoid bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Sphenoid_bone_-_lateral_view.png",
    "pagina": "https://en.wikipedia.org/wiki/Sphenoid_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "etmoides": {
    "file": "etmoides.png",
    "titulo": "Ethmoid bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Orbital_bones.png",
    "pagina": "https://en.wikipedia.org/wiki/Ethmoid_bone",
    "autor": "The original uploader was Je at uwo at English Wikipedia.",
    "licencia": "CC BY 2.5",
    "licencia_url": "https://creativecommons.org/licenses/by/2.5"
  },
  "maxilar": {
    "file": "maxilar.png",
    "titulo": "Maxilla",
    "origen": "https://commons.wikimedia.org/wiki/File:Maxilla_anterior.png",
    "pagina": "https://en.wikipedia.org/wiki/Maxilla",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "cigomatico": {
    "file": "cigomatico.png",
    "titulo": "Zygomatic bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Zygomatic_bone_anterior.png",
    "pagina": "https://en.wikipedia.org/wiki/Zygomatic_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "nasal": {
    "file": "nasal.jpg",
    "titulo": "Nasal bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Illu_facial_bones.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Nasal_bone",
    "autor": "Uploaded by Arcadian",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "lagrimal": {
    "file": "lagrimal.png",
    "titulo": "Lacrimal bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Lacrimal_bone_-_lateral_view6.png",
    "pagina": "https://en.wikipedia.org/wiki/Lacrimal_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "palatino": {
    "file": "palatino.gif",
    "titulo": "Palatine bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Palatine_bone_-_animation_02.gif",
    "pagina": "https://en.wikipedia.org/wiki/Palatine_bone",
    "autor": "Polygon data were generated by Database Center for Life Science (DBCLS)",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "cornete": {
    "file": "cornete.png",
    "titulo": "Inferior nasal concha",
    "origen": "https://commons.wikimedia.org/wiki/File:Gray192.png",
    "pagina": "https://en.wikipedia.org/wiki/Inferior_nasal_concha",
    "autor": "Henry Vandyke Carter",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "vomer": {
    "file": "vomer.jpg",
    "titulo": "Vomer",
    "origen": "https://commons.wikimedia.org/wiki/File:Illu_facial_bones.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Vomer",
    "autor": "Uploaded by Arcadian",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "mandibula": {
    "file": "mandibula.gif",
    "titulo": "Mandible",
    "origen": "https://commons.wikimedia.org/wiki/File:Mandible_bone_-_animation_02.gif",
    "pagina": "https://en.wikipedia.org/wiki/Mandible",
    "autor": "Polygon data were generated by Database Center for Life Science (DBCLS)",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "martillo": {
    "file": "martillo.png",
    "titulo": "Malleus",
    "origen": "https://commons.wikimedia.org/wiki/File:Gray916.png",
    "pagina": "https://en.wikipedia.org/wiki/Malleus",
    "autor": "Henry Vandyke Carter",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "yunque": {
    "file": "yunque.png",
    "titulo": "Incus",
    "origen": "https://commons.wikimedia.org/wiki/File:Gray917.png",
    "pagina": "https://en.wikipedia.org/wiki/Incus",
    "autor": "Henry Vandyke Carter",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "estribo": {
    "file": "estribo.png",
    "titulo": "Stapes",
    "origen": "https://commons.wikimedia.org/wiki/File:Stapes_bone_svg_hariadhi.svg",
    "pagina": "https://en.wikipedia.org/wiki/Stapes",
    "autor": "Hariadhi",
    "licencia": "CC BY-SA 4.0",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hioides": {
    "file": "hioides.jpg",
    "titulo": "Hyoid bone",
    "origen": "https://commons.wikimedia.org/wiki/File:712_Hyoid_Bone.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Hyoid_bone",
    "autor": "OpenStax College",
    "licencia": "CC BY 3.0",
    "licencia_url": "https://creativecommons.org/licenses/by/3.0"
  },
  "atlas": {
    "file": "atlas.png",
    "titulo": "Atlas (anatomy)",
    "origen": "https://commons.wikimedia.org/wiki/File:C1_lateral.png",
    "pagina": "https://en.wikipedia.org/wiki/Atlas_(anatomy)",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "axis": {
    "file": "axis.png",
    "titulo": "Axis (anatomy)",
    "origen": "https://commons.wikimedia.org/wiki/File:C2_lateral.png",
    "pagina": "https://en.wikipedia.org/wiki/Axis_(anatomy)",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "cervicales": {
    "file": "cervicales.png",
    "titulo": "Cervical vertebrae",
    "origen": "https://commons.wikimedia.org/wiki/File:Cervical_vertebrae_lateral2.png",
    "pagina": "https://en.wikipedia.org/wiki/Cervical_vertebrae",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "dorsales": {
    "file": "dorsales.png",
    "titulo": "Thoracic vertebrae",
    "origen": "https://commons.wikimedia.org/wiki/File:Thoracic_vertebrae_back5.png",
    "pagina": "https://en.wikipedia.org/wiki/Thoracic_vertebrae",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "lumbares": {
    "file": "lumbares.png",
    "titulo": "Lumbar vertebrae",
    "origen": "https://commons.wikimedia.org/wiki/File:Lumbar_vertebrae_anterior.png",
    "pagina": "https://en.wikipedia.org/wiki/Lumbar_vertebrae",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "sacro": {
    "file": "sacro.png",
    "titulo": "Sacrum",
    "origen": "https://commons.wikimedia.org/wiki/File:Sacrum_-_anterior_view04.png",
    "pagina": "https://en.wikipedia.org/wiki/Sacrum",
    "autor": "BodyParts3D is made by DBCLS",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "coccix": {
    "file": "coccix.png",
    "titulo": "Coccyx",
    "origen": "https://commons.wikimedia.org/wiki/File:Coccyx_-_anterior_view02.png",
    "pagina": "https://en.wikipedia.org/wiki/Coccyx",
    "autor": "BodyParts3D is made by DBCLS",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "esternon": {
    "file": "esternon.png",
    "titulo": "Sternum",
    "origen": "https://commons.wikimedia.org/wiki/File:Sternum_composition.png",
    "pagina": "https://en.wikipedia.org/wiki/Sternum",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "costilla": {
    "file": "costilla.jpg",
    "titulo": "Rib",
    "origen": "https://commons.wikimedia.org/wiki/File:Costae_-_collection.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Rib",
    "autor": "MAKY.OREL",
    "licencia": "CC0",
    "licencia_url": "http://creativecommons.org/publicdomain/zero/1.0/deed.en"
  },
  "clavicula": {
    "file": "clavicula.png",
    "titulo": "Clavicle",
    "origen": "https://commons.wikimedia.org/wiki/File:Clavicle_-_anterior_view.png",
    "pagina": "https://en.wikipedia.org/wiki/Clavicle",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "escapula": {
    "file": "escapula.png",
    "titulo": "Scapula",
    "origen": "https://commons.wikimedia.org/wiki/File:Pectoral_girdle_front_diagram.svg",
    "pagina": "https://en.wikipedia.org/wiki/Scapula",
    "autor": "LadyofHats Mariana Ruiz Villarreal",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "humero": {
    "file": "humero.png",
    "titulo": "Humerus",
    "origen": "https://commons.wikimedia.org/wiki/File:Humerus_-_anterior_view.png",
    "pagina": "https://en.wikipedia.org/wiki/Humerus",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "radio": {
    "file": "radio.png",
    "titulo": "Radius (bone)",
    "origen": "https://commons.wikimedia.org/wiki/File:Radius_-_anterior_view2.png",
    "pagina": "https://en.wikipedia.org/wiki/Radius_(bone)",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "cubito": {
    "file": "cubito.png",
    "titulo": "Ulna",
    "origen": "https://commons.wikimedia.org/wiki/File:Ulna_-_anterior_view.png",
    "pagina": "https://en.wikipedia.org/wiki/Ulna",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "escafoides": {
    "file": "escafoides.jpg",
    "titulo": "Scaphoid bone",
    "origen": "https://commons.wikimedia.org/wiki/File:AnteriorViewOfRightScaphoid.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Scaphoid_bone",
    "autor": "Adrien Charpy",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "semilunar": {
    "file": "semilunar.png",
    "titulo": "Lunate bone",
    "origen": "https://commons.wikimedia.org/wiki/File:TwoAspectsOfRightLunate.png",
    "pagina": "https://en.wikipedia.org/wiki/Lunate_bone",
    "autor": "Henry Gray",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "piramidal": {
    "file": "piramidal.png",
    "titulo": "Triquetral bone",
    "origen": "https://commons.wikimedia.org/wiki/File:HandSkeletonWithTriqueterumHighlighted.png",
    "pagina": "https://en.wikipedia.org/wiki/Triquetral_bone",
    "autor": "Henry Gray",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "pisiforme": {
    "file": "pisiforme.jpg",
    "titulo": "Pisiform bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Right-sidedPisiform.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Pisiform_bone",
    "autor": "Adrien Charpy",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "trapezoide": {
    "file": "trapezoide.jpg",
    "titulo": "Trapezoid bone",
    "origen": "https://commons.wikimedia.org/wiki/File:RightTrapezoid.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Trapezoid_bone",
    "autor": "Leo Testut",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "grande": {
    "file": "grande.png",
    "titulo": "Capitate bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Right-sidedCapitate.png",
    "pagina": "https://en.wikipedia.org/wiki/Capitate_bone",
    "autor": "Henry Gray",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "ganchoso": {
    "file": "ganchoso.jpg",
    "titulo": "Hamate bone",
    "origen": "https://commons.wikimedia.org/wiki/File:OsCrochuDroit.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Hamate_bone",
    "autor": "Adrien Charpy",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "metacarpianos": {
    "file": "metacarpianos.png",
    "titulo": "Metacarpal bones",
    "origen": "https://commons.wikimedia.org/wiki/File:Metacarpal_bones_%28left_hand%29_01_palmar_view_with_label.png",
    "pagina": "https://en.wikipedia.org/wiki/Metacarpal_bones",
    "autor": "BodyParts3D is made by DBCLS. Rendering the image is by was_a_bee, using Blender.",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "falanges": {
    "file": "falanges.png",
    "titulo": "Phalanx bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Scheme_human_hand_bones-en.svg",
    "pagina": "https://en.wikipedia.org/wiki/Phalanx_bone",
    "autor": "Mariana Ruiz Villarreal (LadyofHats); retouches by Nyks",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "coxal": {
    "file": "coxal.jpg",
    "titulo": "Hip bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Hip_bone_anterior_high-res.jpg",
    "pagina": "https://en.wikipedia.org/wiki/Hip_bone",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "femur": {
    "file": "femur.png",
    "titulo": "Femur",
    "origen": "https://commons.wikimedia.org/wiki/File:Femur_-_anterior_view2.png",
    "pagina": "https://en.wikipedia.org/wiki/Femur",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "rotula": {
    "file": "rotula.png",
    "titulo": "Patella",
    "origen": "https://commons.wikimedia.org/wiki/File:Knee_diagram.svg",
    "pagina": "https://en.wikipedia.org/wiki/Patella",
    "autor": "Mysid",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "tibia": {
    "file": "tibia.png",
    "titulo": "Tibia",
    "origen": "https://commons.wikimedia.org/wiki/File:Tibia_-_frontal_view.png",
    "pagina": "https://en.wikipedia.org/wiki/Tibia",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "peroneo": {
    "file": "peroneo.png",
    "titulo": "Fibula",
    "origen": "https://commons.wikimedia.org/wiki/File:Fibula_-_anterior_view.png",
    "pagina": "https://en.wikipedia.org/wiki/Fibula",
    "autor": "Anatomography",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "astragalo": {
    "file": "astragalo.png",
    "titulo": "Talus bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Subtalar_Joint.svg",
    "pagina": "https://en.wikipedia.org/wiki/Talus_bone",
    "autor": "",
    "licencia": "CC BY-SA 3.0",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  "calcaneo": {
    "file": "calcaneo.png",
    "titulo": "Calcaneus",
    "origen": "https://commons.wikimedia.org/wiki/File:Subtalar_Joint.svg",
    "pagina": "https://en.wikipedia.org/wiki/Calcaneus",
    "autor": "",
    "licencia": "CC BY-SA 3.0",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  "cuboides": {
    "file": "cuboides.png",
    "titulo": "Cuboid bone",
    "origen": "https://commons.wikimedia.org/wiki/File:CuboidOfRightFoot.png",
    "pagina": "https://en.wikipedia.org/wiki/Cuboid_bone",
    "autor": "Henry Gray",
    "licencia": "Public domain",
    "licencia_url": ""
  },
  "cuneiforme_medial": {
    "file": "cuneiforme_medial.gif",
    "titulo": "Medial cuneiform bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Cuneiform_bone_animation01.gif",
    "pagina": "https://en.wikipedia.org/wiki/Cuneiform_bones",
    "autor": "BodyParts3D is made by DBCLS.",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "cuneiforme_intermedio": {
    "file": "cuneiforme_intermedio.gif",
    "titulo": "Intermediate cuneiform bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Cuneiform_bone_animation01.gif",
    "pagina": "https://en.wikipedia.org/wiki/Cuneiform_bones",
    "autor": "BodyParts3D is made by DBCLS.",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "cuneiforme_lateral": {
    "file": "cuneiforme_lateral.gif",
    "titulo": "Lateral cuneiform bone",
    "origen": "https://commons.wikimedia.org/wiki/File:Cuneiform_bone_animation01.gif",
    "pagina": "https://en.wikipedia.org/wiki/Cuneiform_bones",
    "autor": "BodyParts3D is made by DBCLS.",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  },
  "metatarsianos": {
    "file": "metatarsianos.png",
    "titulo": "Metatarsal bones",
    "origen": "https://commons.wikimedia.org/wiki/File:Metatarsal_bones01_-_superior_view.png",
    "pagina": "https://en.wikipedia.org/wiki/Metatarsal_bones",
    "autor": "BodyParts3D is made by DBCLS.",
    "licencia": "CC BY-SA 2.1 jp",
    "licencia_url": "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"
  }
};
